#
# x86_64 - ImmortalWrt 编译工作流
# 调用通用编译工作流
#
name: x86-64

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      NO_DOCKERMAN:
        description: 'Not build luci-app-dockerman'
        required: true
        default: false
        type: boolean
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 16 * * *

permissions:
  contents: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/build-openwrt.yml
    with:
      openwrt_name: immortalwrt
      upload_tag_name: x86-64
      repo_url: https://github.com/immortalwrt/immortalwrt
      repo_branch: master
      config_file: x86-64/.config
      feeds_conf: feeds.conf.default
      diy_p1_sh: x86-64/diy-part1.sh
      diy_p2_sh: x86-64/diy-part2.sh
      release_notes: '- 设备：x86_64 (软路由/虚拟机)\n- 架构：x86-64'
      no_dockerman: ${{ github.event.inputs.NO_DOCKERMAN == 'true' }}
      ssh_enabled: ${{ github.event.inputs.ssh == 'true' }}
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
